name: Triage Stale Issue
author: Alexander Thoukydides
description: Identify any stale issues and label, comment, and close them, as appropriate
branding:
  icon: 'trash-2'
  color: 'blue'

inputs:
  gemini_api_key:
    description: The Google AI Studio Gemini API key
    required: true
    type: string
  issue_number:
    description: The GitHub issue to treat as stale; if not provided, a stale issue is selected based on the number of days since last update
    required: false
    type: number
  dry_run:
    description: Disables actions that modify the issue (adding the comment and minimising previous comments) for testing
    type: boolean
    default: false

runs:
  using: composite

  steps:

  - name: Select stale issue
    id: select
    uses: thoukydides/action-select-stale-issue@v1
    with:
      days_before_stale: 14
      days_before_close: 7
      stale-issue-label: 'stale'
      issue_number: ${{ fromJson(inputs.issue_number) }}

  - name: Summarise and label stale issue ${{ steps.select.outputs.stale_issue_number }}
    if: ${{ steps.select.outputs.stale_issue_number != '' }}
    uses: thoukydides/action-stale-issue-comment@v1
    with:
      gemini_api_key: ${{ inputs.gemini_api_key }}
      issue_number: ${{ steps.select.outputs.stale_issue_number }}
      labels_add: '["stale"]'
      dry_run: ${{ inputs.dry_run }}

  - name: Close stale issue ${{ steps.select.outputs.close_issue_number }}
    if: ${{ steps.select.outputs.close_issue_number != '' }}
    uses: thoukydides/action-post-issue-comment@v1
    with:
      issue_number: ${{ steps.select.outputs.close_issue_number }}
      body: '💤 This issue was closed because it has been stalled for 7 days with no activity.'
      marker: '<!-- action-triage-stale-issue-close -->'
      close_issue: true
      github_token: ${{ inputs.github_token }}
      dry_run: ${{ inputs.dry_run }}